### ISSUE TITLE
Internet Server error 500 

### ISSUE THREAD

**Issue by ysamouhos** [Gradiant/dockerized-kibana#10]
Hello, 

Building for version 7.5.0, 7.5.1, 7.5.2, 7.6.0,7.6.1 and 7.6.2 using the respective elasticsearch service. 

No matter what I do I always get the following error when I try to access 5601. Any clue?

kibana_1  | Debug: internal, implementation, error 
kibana_1  |     TypeError: request.getSavedObjectsClient is not a function
kibana_1  |     at getUiSettingsServiceForRequest (/usr/share/kibana/src/legacy/ui/ui_settings/ui_settings_service_for_request.js:42:38)
kibana_1  |     at server.addMemoizedFactoryToRequest.request (/usr/share/kibana/src/legacy/ui/ui_settings/ui_settings_mixin.js:57:80)
kibana_1  |     at Request.getUiSettingsService (/usr/share/kibana/src/legacy/server/server_extensions/server_extensions_mixin.js:64:35)
kibana_1  |     at Request.getDefaultRoute (/usr/share/kibana/src/legacy/server/http/setup_default_route_provider.js:33:32)
kibana_1  |     at handler (/usr/share/kibana/src/legacy/server/http/index.js:79:36)
kibana_1  |     at module.exports.internals.Manager.execute (/usr/share/kibana/node_modules/hapi/lib/toolkit.js:35:106)
kibana_1  |     at Object.internals.handler (/usr/share/kibana/node_modules/hapi/lib/handler.js:50:48)
kibana_1  |     at exports.execute (/usr/share/kibana/node_modules/hapi/lib/handler.js:35:36)
kibana_1  |     at Request._lifecycle (/usr/share/kibana/node_modules/hapi/lib/request.js:263:62)
kibana_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
kibana_1  | {"type":"error","@timestamp":"2020-05-12T19:54:28Z","tags":[],"pid":6,"level":"error","error":{"message":"request.getSavedObjectsClient is not a function","name":"TypeError","stack":"TypeError: request.getSavedObjectsClient is not a function\n    at getUiSettingsServiceForRequest (/usr/share/kibana/src/legacy/ui/ui_settings/ui_settings_service_for_request.js:42:38)\n    at server.addMemoizedFactoryToRequest.request (/usr/share/kibana/src/legacy/ui/ui_settings/ui_settings_mixin.js:57:80)\n    at Request.getUiSettingsService (/usr/share/kibana/src/legacy/server/server_extensions/server_extensions_mixin.js:64:35)\n    at Request.getDefaultRoute (/usr/share/kibana/src/legacy/server/http/setup_default_route_provider.js:33:32)\n    at handler (/usr/share/kibana/src/legacy/server/http/index.js:79:36)\n    at module.exports.internals.Manager.execute (/usr/share/kibana/node_modules/hapi/lib/toolkit.js:35:106)\n    at Object.internals.handler (/usr/share/kibana/node_modules/hapi/lib/handler.js:50:48)\n    at exports.execute (/usr/share/kibana/node_modules/hapi/lib/handler.js:35:36)\n    at Request._lifecycle (/usr/share/kibana/node_modules/hapi/lib/request.js:263:62)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/","path":"/","href":"/"},"message":"request.getSavedObjectsClient is not a function"}

**Comment by cgiraldo** [comment]
I don't know. I can't replicate your problem.

Have you tried with the official kibana image from elastic without the error?

I have added a docker-compose.yaml example to launch kibana and elasticsearch together.

It works for us for all kibana versions we have released.

**Comment by ysamouhos** [comment]
I am running non dockerized elastic. Let me try running them together dockerized using your yaml and I will let you know.
