### ISSUE TITLE
Fail to install plugin

### ISSUE THREAD

**Issue by sandy-ding** [Gradiant/dockerized-kibana#2]
Hi, I try to install 'gradiant_style.zip' as plugin but failed.
RUN bin/kibana-plugin install file://{FILEPATH}/gradiant_style.zip
SHOW Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by cgiraldo** [comment]
Make sure that gradiant_style.zip file contains a kibana folder with a gradiant_style folder in it.
Also kibana/gradiant_style/package.json must have the correct version of Kibana you are using.

If you are creating a custom docker image, the Dockerfile of the repository should zip the files and install the plugin for you. You need multi-stage builds, that is a feature requiring Docker 17.05 or higher.

**Comment by rgregory1963** [comment]
Hi, I am trying to experiment with this plugin.  I have ES and Kibana installed on Centos7 via RPM.  I used kibana-plugin tool to install.  I see the following in the kibana log:
"Optimization of bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, classification-banner, gradiant_style, kibana, stateSessionStorageRedirect, status_page and timelion complete in 58.18 seconds"
I also see the plugin in the optimize/bundles directory (gradiant_style.css,gradiant_style.bundle.js, gradiant_style.entry.js).  However, I don't see the style changes in Kibana.  Can you provide any helpful insight into why it's not working.  Thx!

**Comment by cgiraldo** [comment]
If you want to explore a working deployment try with this docker commands:

`
docker run --name elasticsearch  -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.1.1
docker run -p 5601:5601 --link elasticsearch -d gradiant/kibana:7.1.1
`

Then open your browser at [http://127.0.0.1:5601](http://127.0.0.1:5601)

This gradiant/kibana:7.1.1 image is build with [this Dockerfile](https://github.com/Gradiant/dockerized-kibana/blob/7.1/Dockerfile).

To debug you can inspect HTML source of kibana webpage. In the Head section should include:

\<link rel="stylesheet" type="text/css" href="/bundles/gradiant_style.style.css"> 

just after \
\<link rel="stylesheet" type="text/css" href="/built_assets/css/plugins/graph/index.light.css">

gradiant_style.style.css should be also served by kibana server. In the previous example should be at [http://127.0.0.1:5601/bundles/gradiant_style.style.css](http://127.0.0.1:5601/bundles/gradiant_style.style.css)
