### ISSUE TITLE
Plugin not visible in Kibana 7.1.1

### ISSUE THREAD

**Issue by rgregory1963** [Gradiant/dockerized-kibana#4]
Hi, I am trying to experiment with 3rd party plugin. I have ES and Kibana 7.1.1 installed on Centos7 via RPM. I used kibana-plugin tool to install this plugin. I see the following in the kibana log:
"Optimization of bundles for graph, monitoring, space_selector, login, logout, logged_out, ml, dashboardViewer, apm, maps, canvas, infra, uptime, **gradiant_style**, kibana, stateSessionStorageRedirect, status_page and timelion complete in 58.18 seconds"
I also see the plugin in the optimize/bundles directory (**gradiant_style.css,gradiant_style.bundle.js, gradiant_style.entry.js)**. However, I don't see the plugin in Kibana. Can you provide any helpful insight into why it's not working. Am I missing a step or is there another troubleshooting technique I can use to understand why plugin doesn't appear.

**Comment by cgiraldo** [comment]
If you want to explore a working deployment try with this docker commands:

`
docker run --name elasticsearch  -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.1.1
docker run -p 5601:5601 --link elasticsearch -d gradiant/kibana:7.1.1
`

Then open your browser at [http://127.0.0.1:5601](http://127.0.0.1:5601)

This gradiant/kibana:7.1.1 image is build with [this Dockerfile](https://github.com/Gradiant/dockerized-kibana/blob/7.1/Dockerfile).

To debug you can inspect HTML source of kibana webpage. In the Head section should include:

\<link rel="stylesheet" type="text/css" href="/bundles/gradiant_style.style.css"> 

just after \
\<link rel="stylesheet" type="text/css" href="/built_assets/css/plugins/graph/index.light.css">

gradiant_style.style.css should be also served by kibana server. In the previous example should be at [http://127.0.0.1:5601/bundles/gradiant_style.style.css](http://127.0.0.1:5601/bundles/gradiant_style.style.css)

**Comment by cgiraldo** [comment]
You also have to patch kibana source code to add a reference to the plugin CSS in kibana html.

For kibana 7.1:

```
sed -i 's/reverse()/reverse(),`${regularBundlePath}\/gradiant_style.style.css`/g' /usr/share/kibana/src/legacy/ui/ui_render/ui_render_mixin.js
```

**Comment by rgregory1963** [comment]
I finally see the plugins!!  Super helpful!  Thanks so much!
