### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by Shikhar1097** [Gradiant/dockerized-kibana#6]
How to build and run this project?

**Comment by cgiraldo** [comment]
checkout the repo tag corresponding to the kibana version to customize (e.g. 7.4.0-oss).

- Build the customized kibana docker image: 
`docker build -t customized-kibana:7.4.0-oss .`

- Deploy kibana docker container with:
`docker run --link YOUR_ELASTICSEARCH_CONTAINER_NAME_OR_ID:elasticsearch -p 5601:5601 customized-kibana:7.4.0-oss`

For detailed info, you can follow kibana official documentation to run your customized kibana as docker:
https://www.elastic.co/guide/en/kibana/7.4/docker.html
