### ISSUE TITLE
v7.6.1 release

### ISSUE THREAD

**Issue by hhko** [Gradiant/dockerized-kibana#7]
I'm using this good plugin. 
Do you have any plans to support v7.6.1?
Thank you

**Comment by cgiraldo** [comment]
Checkout the new 7.6 branch.

We still do not know how to change the throbber image in kibana 7.6+, but the rest of the changes should work.

**Comment by leejongpyo** [comment]
I'm using opendistro and kibana.
opendistro path is ` /usr/share/kibana/src/core/server/rendering/views/styles.js` 
I changed `background-image:` 

```
.kibanaWelcomeLogo {
            width: 60px;
            height: 60px;
            margin: 10px 0 10px 20px;
            background-repeat: no-repeat;
            background-size: contain;
            /* SVG optimized according to http://codepen.io/tigt/post/optimizing-svgs-in-data-uris */
            background-image: url('data:image/svg+xml;base64,PD94bWwgdm');
          }
```

also I think you can use this way :  
- go to : `src/core/server/rendering/views/styles.tsx`
- adding welcomelogo 

reference url : https://discuss.elastic.co/t/customize-logo-in-kibana-7-6/234771/5

@cgiraldo

Thank you.
