### ISSUE TITLE
Changing throbber logo

### ISSUE THREAD

**Issue by Shikhar1097** [Gradiant/dockerized-kibana#8]
In order to change to logo of throbber or loader, 
you can edit the .kibanaWelcomeLogo class in main.less and specify a background image as - 
.kibanaWelcomeLogo * {
  display: none;
}

.kibanaWelcomeLogo {
  background-image: url(url of image);
}

**Comment by cgiraldo** [comment]
commited in ad813763fe65c675ad39ba13a22c51bd5f10139d.
Thanks!
